#include <iostream>
#include <cstdlib>
#include <ctime>

using namespace std;

int selection;

int userguess();
int compguess();

int main()
{
    cout << "Press 1 to guess a number generated by the computer." << endl;
    cout << "Press 2 to have the computer guess your number." << endl;
    cin >> selection;

    switch(selection){
        case 1:
            userguess();
            break;
        case 2:
            compguess();
            break;
        default: cout << "You didn't select anything" << endl;
    }

}

int userguess()
{
    int guess;

    srand(time(0)); // sets random number depending on the time

    int random = 1+(rand()%100); //random variable = (random number / 100) + 1
    int numbguess=0;

    cout << "I'm thinking of a number. Can you guess what it is?" << endl;
    do{
        cin >> guess;

        if(guess>random){
            cout << "Too High. Try again." << endl;
        }

        if(guess<random){
            cout << "Too Low. Try again." << endl;
        }

    numbguess++;
    }while(guess!=random);
    cout << "Well done. The number was " << random << endl;
    cout << "You took " << numbguess << " guesses." <<endl;
    return 0;
}

int compguess()
{
    char higherlower;

    //int startguess = 100;
    int guess = 0;
    int LO = 0;
    int HI = 100;
    int repeatcheck;

    cout << "Press H if the number I guess is higher than your number and L if it is lower." << endl;
    cout << "If I correctly guess then enter C" << endl;
    cout << endl;


    guess= rand() % 100 + 1;
    cout << "Is your number " << guess << "?" << endl;
    cin >> higherlower;

    do {
    switch(higherlower){
        case 'h':
            LO = guess;
            repeatcheck = guess;

            do{
                guess = LO + rand() % (HI - LO);
            }while(repeatcheck==guess);

            cout << "Is your number" << guess << "?" << endl;
            cin >> higherlower;
            break;
        case 'l':
            HI = guess;
            repeatcheck = guess;
            do{
            guess = LO + rand() % (HI - LO);
            }while(repeatcheck==guess);

            cout << "Is your number " << guess << "?" << endl;
            cin >> higherlower;
        }

    }while(higherlower!='c');

}
